from __future__ import annotations

import json
from collections.abc import AsyncIterator
from typing import Any

from caip_responses.loop.tool_executor import ToolExecutor
from caip_responses.models.errors import MaxStepsExceededError
from caip_responses.models.request import CreateResponseRequest
from caip_responses.models.response import Response
from caip_responses.models.streaming import StreamEvent
from caip_responses.providers.base import BaseProvider
from caip_responses.tool_handlers.registry import BuiltinToolRegistry


class AgentLoop:
    """Client-side agentic tool-calling loop for non-OpenAI providers.

    Supports two-tier dispatch:
    1. **Builtin handlers** — synthetic function calls generated by
       ``BuiltinToolRegistry`` (web_search, code_interpreter, shell, etc.)
       are intercepted and executed by the library.
    2. **User handlers** — user-registered function callbacks in the
       ``ToolExecutor`` handle regular function tools.

    Loop:
    1. Call provider with request
    2. If response contains FunctionCallItem(s) → dispatch to handlers
    3. Build FunctionCallOutputItem(s), append to input
    4. Call provider again with augmented input
    5. Repeat until model responds with text only (or max_steps exceeded)

    This is transparent to the user — same responses.create() call.
    """

    def __init__(
        self,
        provider: BaseProvider,
        tool_executor: ToolExecutor,
        max_steps: int = 10,
        builtin_registry: BuiltinToolRegistry | None = None,
    ) -> None:
        self._provider = provider
        self._executor = tool_executor
        self._max_steps = max_steps
        self._builtin = builtin_registry or BuiltinToolRegistry()

    async def run(self, request: CreateResponseRequest) -> Response:
        """Run the agentic loop (non-streaming) until the model is done."""
        current_input = self._ensure_input_list(request.input)
        step = 0

        while step < self._max_steps:
            step += 1

            # Build request with current (possibly augmented) input
            step_request = request.model_copy(update={"input": current_input})
            response = await self._provider.create_response(step_request)

            # Check for function calls
            if not response.has_function_calls:
                return response

            # Execute all function calls (two-tier dispatch)
            fc_items = [
                {
                    "call_id": fc.call_id,
                    "name": fc.name,
                    "arguments": fc.arguments,
                }
                for fc in response.function_calls
            ]
            outputs = await self._execute_function_calls(fc_items)

            # Append the model's output items + our function call outputs to input
            current_input.extend(self._response_output_to_input(response))
            current_input.extend(outputs)

        raise MaxStepsExceededError(self._max_steps)

    async def run_stream(
        self, request: CreateResponseRequest
    ) -> AsyncIterator[StreamEvent]:
        """Run the agentic loop with streaming.

        On each step, we stream events from the provider. If the final
        response contains function calls, we execute them and start a
        new streaming step. All intermediate events are yielded to the
        caller so they see live progress.
        """
        current_input = self._ensure_input_list(request.input)
        step = 0

        while step < self._max_steps:
            step += 1

            step_request = request.model_copy(update={"input": current_input})
            stream = self._provider.create_response_stream(step_request)

            # Collect events and accumulate the response
            events: list[StreamEvent] = []
            async for event in await stream if _is_awaitable(stream) else stream:
                events.append(event)
                yield event

            # Reconstruct function calls from stream events
            fc_items = self._extract_function_calls_from_events(events)

            if not fc_items:
                return  # No function calls → model is done

            # Execute function calls (two-tier dispatch)
            outputs = await self._execute_function_calls(fc_items)

            # Build input items from the streamed response
            streamed_items = self._reconstruct_items_from_events(events)
            current_input.extend(streamed_items)
            current_input.extend(outputs)

        raise MaxStepsExceededError(self._max_steps)

    # ------------------------------------------------------------------
    # Two-tier dispatch
    # ------------------------------------------------------------------

    async def _execute_function_calls(
        self, fc_items: list[dict[str, Any]]
    ) -> list[dict[str, Any]]:
        """Execute function calls: builtin handlers first, then user handlers."""
        outputs: list[dict[str, Any]] = []

        for fc in fc_items:
            fn_name = fc.get("name", "")
            handler = self._builtin.resolve_for_function(fn_name)

            if handler is not None:
                # Builtin tool handler
                try:
                    args = json.loads(fc.get("arguments", "{}"))
                except json.JSONDecodeError:
                    args = {}
                result = await handler.execute(fn_name, args)
                outputs.append({
                    "type": "function_call_output",
                    "call_id": fc.get("call_id", ""),
                    "output": result,
                })
            else:
                # User handler via ToolExecutor
                result = await self._executor.execute(
                    call_id=fc.get("call_id", ""),
                    name=fn_name,
                    arguments=fc.get("arguments", "{}"),
                )
                outputs.append(result)

        return outputs

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _ensure_input_list(
        input_data: str | list[dict[str, Any]]
    ) -> list[dict[str, Any]]:
        """Ensure input is a mutable list."""
        if isinstance(input_data, str):
            return [{"role": "user", "content": input_data}]
        return list(input_data)

    @staticmethod
    def _response_output_to_input(response: Response) -> list[dict[str, Any]]:
        """Convert a Response's output items into input items for the next step.

        Text messages become assistant messages; function calls become
        function_call items that the provider can reconstruct as needed.
        """
        items: list[dict[str, Any]] = []
        for item in response.output:
            if isinstance(item, dict):
                item_type = item.get("type")
            else:
                item_type = getattr(item, "type", None)
                item = item.model_dump() if hasattr(item, "model_dump") else dict(item)

            if item_type == "message":
                # Convert output message → assistant input message
                content = item.get("content", [])
                text_parts = []
                for block in content:
                    if isinstance(block, dict) and block.get("type") == "output_text":
                        text_parts.append(block.get("text", ""))
                if text_parts:
                    items.append({
                        "role": "assistant",
                        "content": "".join(text_parts),
                    })

            elif item_type == "function_call":
                items.append({
                    "type": "function_call",
                    "call_id": item.get("call_id", ""),
                    "name": item.get("name", ""),
                    "arguments": item.get("arguments", "{}"),
                })

        return items

    @staticmethod
    def _extract_function_calls_from_events(
        events: list[StreamEvent],
    ) -> list[dict[str, Any]]:
        """Extract complete function call items from a list of stream events."""
        calls: list[dict[str, Any]] = []
        # Track by output_index
        pending: dict[int, dict[str, Any]] = {}

        for event in events:
            if event.type == "response.output_item.added" and event.item:
                if event.item.get("type") == "function_call":
                    idx = event.output_index or 0
                    pending[idx] = {
                        "call_id": event.item.get("call_id", ""),
                        "name": event.item.get("name", ""),
                        "arguments": "",
                    }

            elif event.type == "response.function_call_arguments.delta":
                idx = event.output_index or 0
                if idx in pending and event.delta:
                    pending[idx]["arguments"] += event.delta

            elif event.type == "response.function_call_arguments.done":
                idx = event.output_index or 0
                if idx in pending:
                    # Use the done event's delta as complete args if we have it
                    if event.delta:
                        pending[idx]["arguments"] = event.delta
                    calls.append(pending.pop(idx))

        # Any remaining pending (shouldn't happen but be safe)
        calls.extend(pending.values())
        return calls

    @staticmethod
    def _reconstruct_items_from_events(
        events: list[StreamEvent],
    ) -> list[dict[str, Any]]:
        """Reconstruct input items from streamed events for the next loop step."""
        items: list[dict[str, Any]] = []
        text_by_index: dict[int, str] = {}
        fn_by_index: dict[int, dict[str, Any]] = {}

        for event in events:
            idx = event.output_index or 0

            if event.type == "response.output_item.added" and event.item:
                item_type = event.item.get("type")
                if item_type == "function_call":
                    fn_by_index[idx] = {
                        "type": "function_call",
                        "call_id": event.item.get("call_id", ""),
                        "name": event.item.get("name", ""),
                        "arguments": "",
                    }

            elif event.type == "response.output_text.delta" and event.delta:
                text_by_index[idx] = text_by_index.get(idx, "") + event.delta

            elif event.type == "response.function_call_arguments.delta" and event.delta:
                if idx in fn_by_index:
                    fn_by_index[idx]["arguments"] += event.delta

            elif event.type == "response.function_call_arguments.done":
                if idx in fn_by_index and event.delta:
                    fn_by_index[idx]["arguments"] = event.delta

        # Build assistant text messages
        for idx in sorted(text_by_index):
            items.append({
                "role": "assistant",
                "content": text_by_index[idx],
            })

        # Build function call items
        for idx in sorted(fn_by_index):
            items.append(fn_by_index[idx])

        return items


def _is_awaitable(obj: Any) -> bool:
    """Check if an object is awaitable (coroutine)."""
    return hasattr(obj, "__await__")
